# Generated by Django 5.0.3 on 2024-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaodoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255)),
                ('temperatura', models.FloatField()),
                ('temperatura_maxima', models.FloatField()),
                ('temperatura_minima', models.FloatField()),
                ('umidade', models.FloatField()),
            ],
        ),
    ]
