# Generated by Django 5.0.3 on 2024-03-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaodoTempo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('temperatura', models.CharField(blank=True, max_length=255)),
                ('temperatura_maxima', models.CharField(blank=True, max_length=255)),
                ('temperatura_minima', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
