# Generated by Django 5.0.3 on 2024-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaodoTempo',
            fields=[
                ('cidade', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(max_length=255)),
                ('temperatura_maxima', models.FloatField(max_length=255)),
                ('temperatura_minima', models.FloatField(max_length=255)),
            ],
        ),
    ]
