# Generated by Django 5.0.3 on 2024-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaodotempo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previsaodotempo',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
    ]
