# Generated by Django 5.0.3 on 2024-03-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsaodotempo',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='previsaodotempo',
            name='umidade',
        ),
    ]
