# Generated by Django 5.0.3 on 2024-03-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_previsaodotempo_id_alter_previsaodotempo_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsaodotempo',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='previsaodotempo',
            name='temperatura',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='previsaodotempo',
            name='temperatura_maxima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='previsaodotempo',
            name='temperatura_minima',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
